---
- name: Kopiert das Controller-System

  hosts: 
    - ubuntu1
    # - ubuntu2
    # - Ubuntu
  vars:
    variablenname: WertderVariable
  
  tasks:
    - name: User qskills soll da sein
      ansible.builtin.user:
        name: qskills
        state: present
      become: yes

    - name: Stelle das Verzeichnis /home/qskills/foo sicher
      ansible.builtin.file:
        name: /home/qskills/foo
        state: directory
        owner: qskills

    - name: Verteile das Inventory
      ansible.builtin.copy:
        src: /home/qskills/inventory
        dest: /home/qskills/foo/inventory
    
    - name: Sicherstellen, dass Ansible installiert ist
      ansible.builtin.package:
        name: ansible
        state: present
      become: yes
